[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Felix BÃ¶hm <felix@felixboehm.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
paho-mqtt = "^1.6.1"
starlette = "^0.21.0"
uvicorn = {extras = ["standard"], version = "^0.18.3"}
asyncio-mqtt = "^0.12.1"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.4.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
