[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Felix BÃ¶hm <felix@felixboehm.dev>"]

[tool.poetry.dependencies]
python = "^3.10"
starlette = "^0.21.0"
uvicorn = {extras = ["standard"], version = "^0.19.0"}
asyncio-mqtt = "^0.14.0"
attrs = "^22.1.0"
Jinja2 = "^3.1.2"
asyncpg = "^0.27.0"
pydantic = "^1.10.2"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.4.7"
mypy = "^0.982"
isort = "^5.10.1"
black = "^22.10.0"
docformatter = "^1.5.0"
sqlfluff = "^1.4.1"
httpx = "^0.23.0"

[tool.black]
preview = true

[tool.isort]
profile = "black"
lines_after_imports = 2

[tool.docformatter]
in-place = true
recursive = true
wrap-summaries = 87
wrap-descriptions = 87

[tool.mypy]
show_error_codes = true
no_implicit_optional = true

[tool.sqlfluff.core]
dialect = "postgres"
templater = "jinja"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
