name: test-server
on:
  push:
    paths:
      - server/**
      - .github/workflows/test-server.yaml
  pull_request:
    paths:
      - server/**
      - .github/workflows/test-server.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached virtual environment
        id: cache
        uses: actions/cache@v3
        with:
          path: server/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('server/poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --with dev --no-root --no-interaction
      - name: Start PostgreSQL
        run: docker docker run -td --rm --name postgres -p 5432:5432 -e POSTGRES_USER="$POSTGRESQL_IDENTIFIER" -e POSTGRES_PASSWORD="$POSTGRESQL_PASSWORD" -e POSTGRES_DB="$POSTGRESQL_DATABASE" postgres:14
        env:
          POSTGRESQL_IDENTIFIER: username
          POSTGRESQL_PASSWORD: 12345678
          POSTGRESQL_DATABASE: database
      - name: Run tests
        run: poetry run pytest -vv --cov=app --cov-report=term-missing tests
        env:
          ENVIRONMENT: test
          COMMIT_SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          POSTGRESQL_URL: localhost
          POSTGRESQL_IDENTIFIER: username
          POSTGRESQL_PASSWORD: 12345678
          POSTGRESQL_DATABASE: database
          MQTT_URL: localhost
          MQTT_PORT: 1883
          MQTT_IDENTIFIER: username
          MQTT_PASSWORD: 12345678
