name: test-server
on:
  push:
    paths:
      - server/**
      - .github/workflows/test-server.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Set up Python
        uses: actions/setup-python@v4 # Uses the Python version in .python-version
        with:
          python-version-file: "server/.python-version"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev --no-root --no-interaction
      - name: Run tests
        run: scripts/test
